server:
  port: 8080
  servlet:
    context-path: /quanly
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/quanlyhs"
    username: root
    password: hoangdanh21
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: truonghocthongminhddd@gmail.com
    password: qiyhfsvgkrgnjbza

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
aes:
  signerKey: "PtitSecretKey123"
upload:
  path: ./user-photos/